id: IE9E018F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T22:16:30+00:00'
last_modified: '2022-06-08T10:20:11.186689+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1653
  title: དཔེ་ཆོས་རིན་པོ་ཆེ་སྤུངས་པའི་འབུམ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BFBB:
      image_group_id: I1KG1753
      title: ''
      total_pages: 366
      order: 1
      base_file: BFBB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
