id: IE9E018F4
legacy_id: P009342
ocr_import_info:
  bdrc_scan_id: W1KG1653
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T22:14:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:33:51.107971+00:00'
last_modified: 2022-08-31 16:34:03.631051
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1653
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1653
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔེ་ཆོས་རིན་པོ་ཆེ་སྤུངས་པའི་འབུམ་འགྲེལ།
  author: པོ་ཏོ་པ་རིན་ཆེན་གསལ།
statistics:
  ocr_word_mean_confidence_index: 0.7837493450719414
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I1KG1753:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1753
      total_pages: 366
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1753.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7837493450719414
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
