id: P009342
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG1653
  title: དཔེ་ཆོས་རིན་པོ་ཆེ་སྤུངས་པའི་འབུམ་འགྲེལ།
  author: ''
  volumes:
    be511ed6e2734747916cb20fc80d3915:
      image_group_id: I1KG1753
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
